name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Process files
        run: |
            npm install bootstrap
            mkdir build
            cp index.html build
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            KEY: ${{ secrets.KEY }}
        with:
            source: "build"
            target: ${{ secrets.ROOT }}
            strip_components: 1
